set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'

Plugin 'scrooloose/nerdtree'
" Plugin 'fatih/vim-go'
" Plugin 'Valloric/YouCompleteMe'
Plugin 'bling/vim-airline'
Plugin 'tpope/vim-fugitive'
Plugin 'kien/ctrlp.vim'
" Plugin 'davidhalter/jedi-vim'
" Plugin 'altercation/vim-colors-solarized'

call vundle#end()

filetype on
filetype plugin on
filetype plugin indent on

set backspace=indent,eol,start
set ruler
set nu
syntax on
set visualbell t_vb=
set novisualbell
"set mouse=a
set t_Co=256

if has('gui_running')
    set background=light
    set guifont=Monospace\ 12
else
    set background=dark
endif

colorscheme evening

set listchars=tab:>-,trail:~,extends:>,precedes:<
set list

set enc=utf-8
set fileencodings=utf-8
set ls=2
set hlsearch

set nobackup
set nowritebackup
set noswapfile

set guioptions-=T

set tabstop=4
set shiftwidth=4
set expandtab
set softtabstop=4
set smartindent

autocmd BufWritePre * :%s/\s\+$//e

map <F3> :NERDTreeToggle<CR>
let NERDTreeIgnore=['\~$', '\.pyc$', '\.pyo$']
let g:ycm_global_ycm_extra_conf = '/home/artem/.vim/bundle/YouCompleteMe/third_party/ycmd/cpp/ycm/.ycm_extra_conf.py'

inoremap <C-space> <C-x><C-o>

let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
let g:ctrlp_working_path_mode = 'ra'

set noeb vb t_vb=

map ё `
map й q
map ц w
map у e
map к r
map е t
map н y
map г u
map ш i
map щ o
map з p
map х [
map ъ ]
map ф a
map ы s
map в d
map а f
map п g
map р h
map о j
map л k
map д l
map ж ;
map э '
map я z
map ч x
map с c
map м v
map и b
map т n
map ь m
map б ,
map ю .
map Ё ~
map Й Q
map Ц W
map У E
map К R
map Е T
map Н Y
map Г U
map Ш I
map Щ O
map З P
map Х {
map Ъ }
map Ф A
map Ы S
map В D
map А F
map П G
map Р H
map О J
map Л K
map Д L
map Ж :
map Э "
map Я Z
map Ч X
map С C
map М V
map И B
map Т N
map Ь M
map Б <
map Ю >
